version: 22
jobs:
- name: Upload to git's
  steps:
  - !PushRepository
    name: Sync Main (GitHub)
    remoteUrl: https://github.com/MushroomSquad/Lollipop
    userName: DonSudak
    passwordSecret: github
    force: false
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
